In [2]:
import numpy as np
import tensorflow as tf

C:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
x=tf.Variable(3, name="x")
y=tf.Variable(6, name="y")

In [4]:
f= x*x*x*y + y + 2

In [5]:
sess=tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
res= sess.run(f)
sess.close

<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x000000000BFF42B0>>

In [6]:
res

170

In [7]:
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    res1=f.eval()    

In [8]:
res1

170

In [9]:
init = tf.global_variables_initializer()

In [10]:
sess=tf.InteractiveSession()

In [11]:
init.run()

In [12]:
result= f.eval()

In [13]:
result

170

In [14]:
sess.close()

In [15]:
x1 = tf.Variable(1)

In [16]:
x1

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [17]:
x1.graph is tf.get_default_graph()

True

In [18]:
graph = tf.Graph()
with graph.as_default():
    x2 = tf.Variable(2)

x2.graph is graph

x2.graph is tf.get_default_graph()

False

In [19]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [20]:
housing= fetch_california_housing()

In [21]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 'California housing dataset.\n\nThe original database is available from StatLib\n\n 

In [22]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [23]:
housing.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [24]:
housing.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [25]:
m,n=np.shape(housing.data)

In [26]:
data_with_bias= np.c_[np.ones((m,1)), housing.data]

In [27]:
data_with_bias

array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [28]:
X=tf.constant(data_with_bias, dtype=tf.float32, name="X")

In [29]:
y=tf.constant(housing.target.reshape(-1,1), dtype= tf.float32, name="y")

In [30]:
XT= tf.transpose(X)

In [31]:
theta= tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [32]:
#theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [33]:
with tf.Session() as sess:
    theta_value= theta.eval()  
    

In [34]:
theta_value

array([[-3.7185181e+01],
       [ 4.3633747e-01],
       [ 9.3952334e-03],
       [-1.0711310e-01],
       [ 6.4479220e-01],
       [-4.0338000e-06],
       [-3.7813708e-03],
       [-4.2348403e-01],
       [-4.3721911e-01]], dtype=float32)

## Implementnting using Gradient Descent

In [35]:
a= tf.random_uniform((2,2), -1, 1, dtype= tf.float32, name= "a")

In [36]:
n_epochs = 1000
learning_rate = 0.01

In [37]:
with tf.Session() as sess:
    a.eval
    print(a)

Tensor("a:0", shape=(2, 2), dtype=float32)


In [38]:
X1= tf.constant(data_with_bias, dtype=tf.float32, name="X1")
y1= tf.constant(housing.target, dtype= tf.float32, name="y")

In [39]:
theta=tf.random_uniform([n+1,1], -1, 1)

In [40]:
y_pred= tf.matmul(X1, theta, name= "predictions")

In [41]:
error = y_pred- y

In [42]:
mse= tf.reduce_mean(tf.square(error), name="mse")

In [43]:
X1= tf.constant(data_with_bias, dtype= tf.float32, name="X1")
y1= tf.constant(housing.target, dtype= tf.float32, name="y")

In [44]:
theta= tf.Variable(tf.random_uniform([n+1,1], -1,1,name="theta"))

In [45]:
y_pred= tf.matmul(X1, theta, name= "predictions")

In [46]:
error= y_pred- y

In [47]:
mse= tf.reduce_mean(tf.square(error), name="mse")

In [48]:
gradients=2/m * tf.matmul(tf.transpose(X1), error)

In [49]:
#training_op= tf.assign(theta, theta- learning_rate*gradients)
training_op = tf.assign(theta, theta - learning_rate * gradients)

In [50]:
init= tf.global_variables_initializer()

In [51]:
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
    sess.run(training_op)
    best_theta = theta.eval()

Epoch 0 MSE = 2821822.8
Epoch 100 MSE = 2821822.8
Epoch 200 MSE = 2821822.8
Epoch 300 MSE = 2821822.8
Epoch 400 MSE = 2821822.8
Epoch 500 MSE = 2821822.8
Epoch 600 MSE = 2821822.8
Epoch 700 MSE = 2821822.8
Epoch 800 MSE = 2821822.8
Epoch 900 MSE = 2821822.8


In [52]:
np.shape(housing.target)

(20640,)

In [53]:
np.reshape(housing.target, (-1,1))

array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]])

In [54]:
np.shape(housing.target)

(20640,)

In [55]:
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5

In [56]:
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})

In [57]:
print(B_val_1)

[[6. 7. 8.]]


In [58]:
print(B_val_2)

[[ 9. 10. 11.]
 [12. 13. 14.]]


## Implementing Mini-batch gradient descent

In [59]:
X = tf.placeholder(tf.float32, shape=(None, n + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")

In [60]:
batch_size = 100
n_batches = int(np.ceil(m / batch_size))

In [ ]:
def fetch_batch(epoch, batch_index, batch_size):
    return X_batch, y_batch
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = fetch_batch(epoch, batch_index, batch_size)
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
            best_theta = theta.eval()